name: Node.js CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: docker_buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      id: docker_build
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker buildx build --platform linux/amd64,linux/arm64 -t my-docker-username/node-docker-app:latest . --push
